component/zeebe:
  - changed-files:
    - any-glob-to-any-file:
        - '.github/ISSUE_TEMPLATE/zeebe-*'
        - '.github/actions/**'
        - '.github/renovate.json'
        - '.github/workflows/zeebe-*'
        - 'Dockerfile'
        - 'bom/*'
        - 'build-tools/**'
        - 'clients/**'
        - 'dist/**'
        - 'monitor/**'
        - 'parent/*'
        - 'pom.xml'
        - 'spring-boot-starter-camunda-sdk/**'
        - 'zeebe/**'
component/operate:
  - changed-files:
    - any-glob-to-any-file:
        - '.ci/**'
        - '.github/ISSUE_TEMPLATE/operate-*'
        - '.github/actions/**'
        - '.github/renovate.json'
        - '.github/workflows/operate-*'
        - 'bom/*'
        - 'distro/**'
        - 'operate.Dockerfile'
        - 'operate/**'
        - 'parent/*'
        - 'pom.xml'
